### ISSUE TITLE
Handle Fragpipe / msfragger table

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS_App#13]
Handle Fragpipe intensity output. See attached.

intensity columns START with experiment name (here 1,2,3..)

"Gene" column can be empty
[combined_protein.txt](https://github.com/FabioBedin/QProMS_App/files/11736302/combined_protein.txt)

**Comment by grandrea** [comment]
Here it's with "Intensity" but otherwise it can be "MaxLFQ"

**Comment by grandrea** [comment]
fragpipe contaminants are from CRAPome https://www.thegpm.org/crap/

**Comment by grandrea** [comment]
The fragpipe default output. Names need not be unique. Default name "combined_protein.tsv"
[fragpipe_combined_protein.txt](https://github.com/FabioBedin/QProMS_App/files/12499012/fragpipe_combined_protein.txt)

**Comment by FabioBedin** [comment]
Implemented feature.
