### ISSUE TITLE
PCA page 

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS_App#23]
I would write "principal component analysis" on the plot titles

I would add at the bottom of the big blue boxes "percentage variance explained" or something that clarifies what that number is.

PC1 -> principal component 1 in the blue box

Just small things to spell it out more if possible

(forse ne avevamo già discusso ed ero stato cassato, in qual caso, chiudi pure la issue)

**Comment by FabioBedin** [comment]
add new extended labes
