### ISSUE TITLE
multivariate page crash

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS_App#27]
With this file (set condirions to plus1-6 and minus1-6), all default, try to do multivariate.
[proteinGroups.txt](https://github.com/FabioBedin/QProMS_App/files/12843681/proteinGroups.txt)

**Comment by FabioBedin** [comment]
I see, the problem would seem to be due to the fact that more clusters were required than the number of significant proteins. I will try to fix it as soon as possible.

**Comment by FabioBedin** [comment]
fixed
