### ISSUE TITLE
Imputation settings hidden in imputation page

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS_App#3]
the settings for imputation are too hidden in imputation page and they are also in the options of the panel "effects of imputations:after" perhaps we need to move this to its own button or to anyways give the user a button to "perform imputation" with the given settings. Or as wheel in the very first panel, missing data counts. It is not clear at all where to look for imputation settings

**Comment by FabioBedin** [comment]
I moved the imputations to an accordion visible on the page.
