### ISSUE TITLE
multiple volcano plot share y axis

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS_App#7]
share y axis in multiple volcano plot or it's very hard to catch that they are different.
If possible, use only one label all the way to the left.

**Comment by grandrea** [comment]
i mean share ranges

**Comment by grandrea** [comment]
maybe there should be a box to tick in the wheels to enable this. Because I may also want to have a common x axis range

**Comment by FabioBedin** [comment]
add the possibility con plot all volcanos with same x and y axis
