### ISSUE TITLE
upload page - print error message rather than "server disconnected" upon upload of wrong file

### ISSUE THREAD

**Issue by grandrea** [FabioBedin/QProMS_App#9]
If I upload a file that is somehow not formatted correctly, I get "server disconnected" without any information that something has gone wrong. If I upload a proteinGroups without gene names or with non-human gene names, the same thing happens.

Files from other search engine also seem to cause this.

**Comment by FabioBedin** [comment]
add Toast message if file fails to meet the requirements.
